# Generated by Django 5.1.7 on 2025-05-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
    ]
