# Generated by Django 5.1.7 on 2025-05-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0004_alter_orderproduct_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default='2013-06-09 00:00:00', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
