# Generated by Django 5.1.7 on 2025-05-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineStore', '0005_remove_order_date_order_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.IntegerField(null=True, verbose_name='Полная стоимость'),
        ),
    ]
